apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-connection
  name: udaconnect-connection
spec:
  ports:
  - name: "50051"
    port: 50051
    targetPort: 50051
    nodePort: 30003
  selector:
    service: udaconnect-connection
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-connection
  name: udaconnect-connection
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-connection
  template:
    metadata:
      labels:
        service: udaconnect-connection
    spec:
      containers:
      - image: rogersacchelli/ud064-udaconnect-connection:latest
        name: udaconnect-connection
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "256m"
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
